spring:
  datasource:
    url: jdbc:mysql://****/seckill?serverTimezone=GMT%2B8&&useCursorFetch=true&&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 127.0.0.1
    port: 6379
    password:

mybatis:
  mapper-locations: classpath:mapper/*.xml